// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma migrations need a direct (non-pgbouncer) connection.
    // On Neon: set DATABASE_URL_UNPOOLED; for other providers DATABASE_URL is fine.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["OBRA_DATABASE_URL_UNPOOLED"] ??
      process.env["DATABASE_URL"] ??
      process.env["OBRA_DATABASE_URL"] ??
      process.env["OBRA_POSTGRES_URL"],
  },
});
