export type ServiceCategory = {
  id: string;
  nameEs: string;
  nameCa: string;
  nameEn: string;
  icon: string;
  services: ServiceItem[];
};

export type ServiceItem = {
  id: string;
  nameEs: string;
  nameCa: string;
  nameEn: string;
  descEs: string;
  descCa: string;
  descEn: string;
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "obra-nueva",
    nameEs: "Obra Nueva",
    nameCa: "Obra Nova",
    nameEn: "New Build",
    icon: "🏗️",
    services: [
      {
        id: "viviendas-unifamiliares",
        nameEs: "Construcción de viviendas unifamiliares",
        nameCa: "Construcció d'habitatges unifamiliars",
        nameEn: "Single-family home construction",
        descEs: "Construimos tu hogar desde cero con los más altos estándares.",
        descCa: "Construïm la teva llar des de zero amb els més alts estàndards.",
        descEn: "We build your home from scratch to the highest standards.",
      },
      {
        id: "edificios-plurifamiliares",
        nameEs: "Construcción de edificios plurifamiliares",
        nameCa: "Construcció d'edificis plurifamiliars",
        nameEn: "Multi-family building construction",
        descEs: "Proyectos residenciales de gran envergadura con calidad certificada.",
        descCa: "Projectes residencials de gran envergadura amb qualitat certificada.",
        descEn: "Large-scale residential projects with certified quality.",
      },
      {
        id: "locales-comerciales-nueva",
        nameEs: "Construcción de locales comerciales",
        nameCa: "Construcció de locals comercials",
        nameEn: "Commercial premises construction",
        descEs: "Espacios comerciales modernos y funcionales adaptados a tu negocio.",
        descCa: "Espais comercials moderns i funcionals adaptats al teu negoci.",
        descEn: "Modern functional commercial spaces tailored to your business.",
      },
      {
        id: "naves-industriales",
        nameEs: "Construcción de naves industriales",
        nameCa: "Construcció de naus industrials",
        nameEn: "Industrial warehouse construction",
        descEs: "Naves industriales a medida para optimizar tus operaciones.",
        descCa: "Naus industrials a mida per optimitzar les teves operacions.",
        descEn: "Custom industrial warehouses to optimise your operations.",
      },
      {
        id: "oficinas",
        nameEs: "Construcción de oficinas",
        nameCa: "Construcció d'oficines",
        nameEn: "Office construction",
        descEs: "Oficinas de alta calidad que potencian la productividad.",
        descCa: "Oficines d'alta qualitat que potencien la productivitat.",
        descEn: "High-quality offices that boost productivity.",
      },
      {
        id: "llave-en-mano",
        nameEs: "Proyectos llave en mano",
        nameCa: "Projectes llave en mà",
        nameEn: "Turnkey projects",
        descEs: "Nos encargamos de todo: diseño, licencias, construcción y entrega.",
        descCa: "Ens encarreguem de tot: disseny, llicències, construcció i entrega.",
        descEn: "We handle everything: design, permits, construction and handover.",
      },
      {
        id: "garajes-aparcamientos",
        nameEs: "Construcción de garajes y aparcamientos",
        nameCa: "Construcció de garatges i aparcaments",
        nameEn: "Garage and parking construction",
        descEs: "Soluciones de aparcamiento eficientes para residencias y negocios.",
        descCa: "Solucions d'aparcament eficients per a residències i negocis.",
        descEn: "Efficient parking solutions for residences and businesses.",
      },
    ],
  },
  {
    id: "reformas-integrales",
    nameEs: "Reformas Integrales",
    nameCa: "Reformes Integrals",
    nameEn: "Full Renovations",
    icon: "🔨",
    services: [
      {
        id: "reforma-pisos",
        nameEs: "Reforma integral de pisos",
        nameCa: "Reforma integral de pisos",
        nameEn: "Full flat renovation",
        descEs: "Transformamos tu piso completamente con acabados de primera calidad.",
        descCa: "Transformem el teu pis completament amb acabats de primera qualitat.",
        descEn: "We fully transform your flat with top-quality finishes.",
      },
      {
        id: "reforma-casas",
        nameEs: "Reforma integral de casas",
        nameCa: "Reforma integral de cases",
        nameEn: "Full house renovation",
        descEs: "Renovación completa de tu casa respetando tu presupuesto.",
        descCa: "Renovació completa de la teva casa respectant el teu pressupost.",
        descEn: "Complete home renovation within your budget.",
      },
      {
        id: "reforma-locales",
        nameEs: "Reforma integral de locales comerciales",
        nameCa: "Reforma integral de locals comercials",
        nameEn: "Full commercial premises renovation",
        descEs: "Renovamos tu local para maximizar el impacto en tus clientes.",
        descCa: "Renovem el teu local per maximitzar l'impacte en els teus clients.",
        descEn: "We renovate your premises to maximise client impact.",
      },
      {
        id: "reforma-oficinas",
        nameEs: "Reforma de oficinas",
        nameCa: "Reforma d'oficines",
        nameEn: "Office renovation",
        descEs: "Modernizamos tus espacios de trabajo para mejorar el ambiente laboral.",
        descCa: "Modernitzem els teus espais de treball per millorar l'ambient laboral.",
        descEn: "We modernise your workspaces to improve the working environment.",
      },
      {
        id: "rehabilitacion-historicos",
        nameEs: "Rehabilitación de edificios históricos",
        nameCa: "Rehabilitació d'edificis històrics",
        nameEn: "Historic building rehabilitation",
        descEs: "Especialistas en restaurar el patrimonio arquitectónico con respeto.",
        descCa: "Especialistes en restaurar el patrimoni arquitectònic amb respecte.",
        descEn: "Specialists in restoring architectural heritage with respect.",
      },
      {
        id: "ampliacion-viviendas",
        nameEs: "Ampliación y extensión de viviendas",
        nameCa: "Ampliació i extensió d'habitatges",
        nameEn: "Home extension",
        descEs: "Aumenta el espacio de tu hogar con soluciones arquitectónicas creativas.",
        descCa: "Augmenta l'espai de la teva llar amb solucions arquitectòniques creatives.",
        descEn: "Expand your living space with creative architectural solutions.",
      },
    ],
  },
  {
    id: "fachadas-estructuras",
    nameEs: "Rehabilitación de Fachadas y Estructuras",
    nameCa: "Rehabilitació de Façanes i Estructures",
    nameEn: "Facade & Structural Rehabilitation",
    icon: "🏛️",
    services: [
      {
        id: "rehabilitacion-fachadas",
        nameEs: "Rehabilitación de fachadas",
        nameCa: "Rehabilitació de façanes",
        nameEn: "Facade rehabilitation",
        descEs: "Recuperamos el aspecto original y protegemos tu edificio del exterior.",
        descCa: "Recuperem l'aspecte original i protegim el teu edifici de l'exterior.",
        descEn: "We restore the original appearance and protect your building.",
      },
      {
        id: "impermeabilizacion",
        nameEs: "Impermeabilización de cubiertas y terrazas",
        nameCa: "Impermeabilització de cobertes i terrasses",
        nameEn: "Waterproofing roofs and terraces",
        descEs: "Impermeabilización profesional para prevenir filtraciones y humedades.",
        descCa: "Impermeabilització professional per prevenir filtracions i humitats.",
        descEn: "Professional waterproofing to prevent leaks and damp.",
      },
      {
        id: "reparacion-estructural",
        nameEs: "Reparación estructural y refuerzo",
        nameCa: "Reparació estructural i reforç",
        nameEn: "Structural repair and reinforcement",
        descEs: "Garantizamos la seguridad estructural de tu edificio.",
        descCa: "Garantim la seguretat estructural del teu edifici.",
        descEn: "We guarantee the structural safety of your building.",
      },
      {
        id: "restauracion-edificios",
        nameEs: "Restauración de edificios",
        nameCa: "Restauració d'edificis",
        nameEn: "Building restoration",
        descEs: "Devolvemos el esplendor original a edificios con valor histórico.",
        descCa: "Retornem l'esplendor original a edificis amb valor històric.",
        descEn: "We restore the original splendour of historically significant buildings.",
      },
      {
        id: "aislamiento-sate",
        nameEs: "Aislamiento térmico y acústico (SATE)",
        nameCa: "Aïllament tèrmic i acústic (SATE)",
        nameEn: "Thermal and acoustic insulation (ETICS)",
        descEs: "Mejora la eficiencia energética y el confort de tu edificio con SATE.",
        descCa: "Millora l'eficiència energètica i el confort del teu edifici amb SATE.",
        descEn: "Improve your building's energy efficiency and comfort with ETICS.",
      },
      {
        id: "pintura-fachadas",
        nameEs: "Pintura de fachadas",
        nameCa: "Pintura de façanes",
        nameEn: "Facade painting",
        descEs: "Acabados de alta durabilidad que renuevan la imagen de tu edificio.",
        descCa: "Acabats d'alta durabilitat que renoven la imatge del teu edifici.",
        descEn: "High-durability finishes that renew your building's appearance.",
      },
    ],
  },
  {
    id: "instalaciones",
    nameEs: "Instalaciones",
    nameCa: "Instal·lacions",
    nameEn: "Installations",
    icon: "⚡",
    services: [
      {
        id: "instalacion-electrica",
        nameEs: "Instalación eléctrica (BT y AT)",
        nameCa: "Instal·lació elèctrica (BT i AT)",
        nameEn: "Electrical installation (LV and HV)",
        descEs: "Instalaciones eléctricas seguras y certificadas para todo tipo de edificios.",
        descCa: "Instal·lacions elèctriques segures i certificades per a tot tipus d'edificis.",
        descEn: "Safe, certified electrical installations for all building types.",
      },
      {
        id: "fontaneria-saneamiento",
        nameEs: "Instalación de fontanería y saneamiento",
        nameCa: "Instal·lació de fontaneria i sanejament",
        nameEn: "Plumbing and sanitation installation",
        descEs: "Fontanería de alta calidad para garantizar el correcto suministro de agua.",
        descCa: "Fontaneria d'alta qualitat per garantir el correcte subministrament d'aigua.",
        descEn: "High-quality plumbing to ensure correct water supply.",
      },
      {
        id: "climatizacion-hvac",
        nameEs: "Instalación de calefacción y climatización (HVAC)",
        nameCa: "Instal·lació de calefacció i climatització (HVAC)",
        nameEn: "Heating and air conditioning installation (HVAC)",
        descEs: "Sistemas HVAC eficientes para el máximo confort todo el año.",
        descCa: "Sistemes HVAC eficients per al màxim confort tot l'any.",
        descEn: "Efficient HVAC systems for maximum year-round comfort.",
      },
      {
        id: "instalacion-gas",
        nameEs: "Instalación de gas",
        nameCa: "Instal·lació de gas",
        nameEn: "Gas installation",
        descEs: "Instalaciones de gas certificadas con todos los protocolos de seguridad.",
        descCa: "Instal·lacions de gas certificades amb tots els protocols de seguretat.",
        descEn: "Certified gas installations with full safety protocols.",
      },
      {
        id: "solar-fotovoltaica",
        nameEs: "Instalación de energía solar (fotovoltaica)",
        nameCa: "Instal·lació d'energia solar (fotovoltaica)",
        nameEn: "Solar energy installation (photovoltaic)",
        descEs: "Reduce tu factura eléctrica con instalaciones solares de última generación.",
        descCa: "Redueix la teva factura elèctrica amb instal·lacions solars d'última generació.",
        descEn: "Reduce your electricity bill with next-generation solar installations.",
      },
      {
        id: "domotica",
        nameEs: "Domótica y automatización del hogar",
        nameCa: "Domòtica i automatització de la llar",
        nameEn: "Home automation",
        descEs: "Convierte tu hogar en un espacio inteligente y eficiente.",
        descCa: "Converteix la teva llar en un espai intel·ligent i eficient.",
        descEn: "Turn your home into a smart, efficient living space.",
      },
      {
        id: "ascensores",
        nameEs: "Instalación de ascensores",
        nameCa: "Instal·lació d'ascensors",
        nameEn: "Lift installation",
        descEs: "Instalación y mantenimiento de ascensores para edificios residenciales y comerciales.",
        descCa: "Instal·lació i manteniment d'ascensors per a edificis residencials i comercials.",
        descEn: "Lift installation and maintenance for residential and commercial buildings.",
      },
    ],
  },
  {
    id: "acabados-interiores",
    nameEs: "Acabados Interiores",
    nameCa: "Acabats Interiors",
    nameEn: "Interior Finishes",
    icon: "🎨",
    services: [
      {
        id: "alicatado-solados",
        nameEs: "Alicatado y solados (azulejos y suelos)",
        nameCa: "Enrajolat i solats (rajoles i terres)",
        nameEn: "Tiling and flooring",
        descEs: "Colocación de azulejos y suelos con acabados perfectos.",
        descCa: "Col·locació de rajoles i terres amb acabats perfectes.",
        descEn: "Tile and floor laying with perfect finishes.",
      },
      {
        id: "pintura-interior",
        nameEs: "Pintura interior",
        nameCa: "Pintura interior",
        nameEn: "Interior painting",
        descEs: "Pinturas de alta calidad que transforman completamente los espacios.",
        descCa: "Pintures d'alta qualitat que transformen completament els espais.",
        descEn: "High-quality paints that completely transform spaces.",
      },
      {
        id: "escayola-yeso-pladur",
        nameEs: "Escayola, yeso y pladur",
        nameCa: "Escaiola, guix i pladur",
        nameEn: "Plasterwork and drylining",
        descEs: "Trabajos de escayola, yeso y pladur para acabados impecables.",
        descCa: "Treballs d'escaiola, guix i pladur per a acabats impecables.",
        descEn: "Plasterwork and drylining for impeccable finishes.",
      },
      {
        id: "carpinteria-madera",
        nameEs: "Carpintería de madera a medida",
        nameCa: "Fusteria de fusta a mida",
        nameEn: "Custom woodwork",
        descEs: "Puertas, armarios y mobiliario de madera a medida con diseño exclusivo.",
        descCa: "Portes, armaris i mobiliari de fusta a mida amb disseny exclusiu.",
        descEn: "Custom-made doors, wardrobes and wooden furniture with exclusive design.",
      },
      {
        id: "carpinteria-metalica",
        nameEs: "Carpintería metálica y cerrajería",
        nameCa: "Fusteria metàl·lica i serralleria",
        nameEn: "Metal joinery and locksmithing",
        descEs: "Estructuras metálicas, rejas y puertas de alta seguridad.",
        descCa: "Estructures metàl·liques, reixes i portes d'alta seguretat.",
        descEn: "Metal structures, grilles and high-security doors.",
      },
      {
        id: "parquet-laminados",
        nameEs: "Instalación de parquet y suelos laminados",
        nameCa: "Instal·lació de parquet i terres laminats",
        nameEn: "Parquet and laminate flooring installation",
        descEs: "Suelos de parquet y laminados con instalación profesional.",
        descCa: "Terres de parquet i laminats amb instal·lació professional.",
        descEn: "Parquet and laminate floors with professional installation.",
      },
      {
        id: "falsos-techos",
        nameEs: "Falsos techos",
        nameCa: "Falsos sostres",
        nameEn: "Suspended ceilings",
        descEs: "Falsos techos que mejoran el aislamiento y la estética de los espacios.",
        descCa: "Falsos sostres que milloren l'aïllament i l'estètica dels espais.",
        descEn: "Suspended ceilings that improve insulation and aesthetics.",
      },
    ],
  },
  {
    id: "banos-cocinas",
    nameEs: "Baños y Cocinas",
    nameCa: "Banys i Cuines",
    nameEn: "Bathrooms & Kitchens",
    icon: "🚿",
    services: [
      {
        id: "reforma-banos",
        nameEs: "Reforma de baños completa",
        nameCa: "Reforma de banys completa",
        nameEn: "Full bathroom renovation",
        descEs: "Transformamos tu baño en un espacio moderno y funcional.",
        descCa: "Transformem el teu bany en un espai modern i funcional.",
        descEn: "We transform your bathroom into a modern, functional space.",
      },
      {
        id: "reforma-cocinas",
        nameEs: "Reforma de cocinas completa",
        nameCa: "Reforma de cuines completa",
        nameEn: "Full kitchen renovation",
        descEs: "Cocinas de diseño con funcionalidad y calidad superiores.",
        descCa: "Cuines de disseny amb funcionalitat i qualitat superiors.",
        descEn: "Designer kitchens with superior functionality and quality.",
      },
      {
        id: "sanitarios-griferia",
        nameEs: "Instalación de sanitarios y grifería",
        nameCa: "Instal·lació de sanitaris i aixeteria",
        nameEn: "Sanitary ware and tap installation",
        descEs: "Instalación de sanitarios y grifería de las mejores marcas.",
        descCa: "Instal·lació de sanitaris i aixeteria de les millors marques.",
        descEn: "Installation of top-brand sanitary ware and taps.",
      },
      {
        id: "diseno-cocinas",
        nameEs: "Diseño y equipamiento de cocinas",
        nameCa: "Disseny i equipament de cuines",
        nameEn: "Kitchen design and fitting",
        descEs: "Diseño personalizado y equipamiento completo de cocinas a medida.",
        descCa: "Disseny personalitzat i equipament complet de cuines a mida.",
        descEn: "Custom kitchen design and complete fitting to your specifications.",
      },
    ],
  },
  {
    id: "urbanizacion-exterior",
    nameEs: "Urbanización y Exterior",
    nameCa: "Urbanització i Exterior",
    nameEn: "Landscaping & Exterior",
    icon: "🌿",
    services: [
      {
        id: "piscinas",
        nameEs: "Construcción de piscinas",
        nameCa: "Construcció de piscines",
        nameEn: "Swimming pool construction",
        descEs: "Piscinas a medida para disfrutar del clima mediterráneo.",
        descCa: "Piscines a mida per gaudir del clima mediterrani.",
        descEn: "Custom swimming pools to enjoy the Mediterranean climate.",
      },
      {
        id: "paisajismo",
        nameEs: "Paisajismo y jardinería",
        nameCa: "Paisatgisme i jardineria",
        nameEn: "Landscaping and gardening",
        descEs: "Creamos jardines espectaculares adaptados a cada espacio.",
        descCa: "Creem jardins espectaculars adaptats a cada espai.",
        descEn: "We create spectacular gardens tailored to each space.",
      },
      {
        id: "pavimentacion-jardines",
        nameEs: "Pavimentación de jardines y patios",
        nameCa: "Pavimentació de jardins i patis",
        nameEn: "Garden and patio paving",
        descEs: "Pavimentos exteriores duraderos con materiales de primera calidad.",
        descCa: "Paviments exteriors duradors amb materials de primera qualitat.",
        descEn: "Durable exterior paving with top-quality materials.",
      },
      {
        id: "vallado-cerramiento",
        nameEs: "Vallado y cerramiento de parcelas",
        nameCa: "Tancat i tancament de parcel·les",
        nameEn: "Plot fencing and enclosure",
        descEs: "Soluciones de cerramiento que combinan seguridad y estética.",
        descCa: "Solucions de tancament que combinen seguretat i estètica.",
        descEn: "Enclosure solutions combining security and aesthetics.",
      },
      {
        id: "terrazas-pergolas",
        nameEs: "Construcción de terrazas y pérgolas",
        nameCa: "Construcció de terrasses i pèrgoles",
        nameEn: "Terrace and pergola construction",
        descEs: "Terrazas y pérgolas para disfrutar al máximo del exterior.",
        descCa: "Terrasses i pèrgoles per gaudir al màxim de l'exterior.",
        descEn: "Terraces and pergolas to make the most of outdoor living.",
      },
      {
        id: "iluminacion-exterior",
        nameEs: "Iluminación exterior",
        nameCa: "Il·luminació exterior",
        nameEn: "Exterior lighting",
        descEs: "Proyectos de iluminación exterior que realzan la belleza de tu propiedad.",
        descCa: "Projectes d'il·luminació exterior que realcen la bellesa de la teva propietat.",
        descEn: "Exterior lighting projects that enhance your property's beauty.",
      },
    ],
  },
  {
    id: "obras-civiles",
    nameEs: "Obras Civiles y Especiales",
    nameCa: "Obres Civils i Especials",
    nameEn: "Civil & Special Works",
    icon: "🏗️",
    services: [
      {
        id: "movimiento-tierras",
        nameEs: "Movimiento de tierras y excavaciones",
        nameCa: "Moviment de terres i excavacions",
        nameEn: "Earthmoving and excavation",
        descEs: "Excavaciones y movimiento de tierras con maquinaria de última generación.",
        descCa: "Excavacions i moviment de terres amb maquinària d'última generació.",
        descEn: "Earthmoving and excavation with state-of-the-art machinery.",
      },
      {
        id: "cimentaciones",
        nameEs: "Cimentaciones y estructuras de hormigón",
        nameCa: "Fonamentacions i estructures de formigó",
        nameEn: "Foundations and concrete structures",
        descEs: "Cimentaciones sólidas que garantizan la durabilidad de tu construcción.",
        descCa: "Fonamentacions sòlides que garanteixen la durabilitat de la teva construcció.",
        descEn: "Solid foundations guaranteeing the durability of your construction.",
      },
      {
        id: "muros-contencion",
        nameEs: "Construcción de muros de contención",
        nameCa: "Construcció de murs de contenció",
        nameEn: "Retaining wall construction",
        descEs: "Muros de contención seguros y duraderos para todo tipo de terrenos.",
        descCa: "Murs de contenció segurs i duradors per a tot tipus de terrenys.",
        descEn: "Safe, durable retaining walls for all terrain types.",
      },
      {
        id: "obras-urbanizacion",
        nameEs: "Obras de urbanización y viales",
        nameCa: "Obres d'urbanització i vials",
        nameEn: "Urbanisation and road works",
        descEs: "Infraestructuras urbanas de calidad para comunidades y urbanizaciones.",
        descCa: "Infraestructures urbanes de qualitat per a comunitats i urbanitzacions.",
        descEn: "Quality urban infrastructure for communities and developments.",
      },
      {
        id: "accesibilidad",
        nameEs: "Accesibilidad: rampas y ascensores adaptados",
        nameCa: "Accessibilitat: rampes i ascensors adaptats",
        nameEn: "Accessibility: ramps and adapted lifts",
        descEs: "Soluciones de accesibilidad que garantizan la movilidad de todos.",
        descCa: "Solucions d'accessibilitat que garanteixen la mobilitat de tots.",
        descEn: "Accessibility solutions guaranteeing mobility for everyone.",
      },
      {
        id: "certificacion-energetica",
        nameEs: "Certificación energética de edificios",
        nameCa: "Certificació energètica d'edificis",
        nameEn: "Building energy certification",
        descEs: "Obtenemos la certificación energética de tu edificio de forma ágil.",
        descCa: "Obtenim la certificació energètica del teu edifici de forma àgil.",
        descEn: "We obtain your building's energy certificate efficiently.",
      },
      {
        id: "licencias-permisos",
        nameEs: "Gestión de licencias y permisos de obra",
        nameCa: "Gestió de llicències i permisos d'obra",
        nameEn: "Building permits and licences management",
        descEs: "Gestionamos todos los trámites administrativos para tu obra.",
        descCa: "Gestionem tots els tràmits administratius per a la teva obra.",
        descEn: "We manage all administrative procedures for your build.",
      },
    ],
  },
  {
    id: "hormigonado-estructuras",
    nameEs: "Hormigonado y Estructuras",
    nameCa: "Formigonat i Estructures",
    nameEn: "Concrete Work & Structures",
    icon: "🏗️",
    services: [
      {
        id: "vertido-colado-hormigon",
        nameEs: "Vertido y colado de hormigón",
        nameCa: "Abocament i formigonat",
        nameEn: "Concrete pouring and casting",
        descEs: "Ejecución profesional de hormigonado in situ para suelos, pilares, muros y estructuras.",
        descCa: "Execució professional de formigonat in situ per a terres, pilars, murs i estructures.",
        descEn: "Professional on-site concrete pouring for floors, columns, walls and structures.",
      },
      {
        id: "soleras-losas-hormigon",
        nameEs: "Soleras y losas de hormigón",
        nameCa: "Soleres i lloses de formigó",
        nameEn: "Concrete slabs and floor slabs",
        descEs: "Soleras y losas resistentes para uso industrial, residencial y comercial.",
        descCa: "Soleres i lloses resistents per a ús industrial, residencial i comercial.",
        descEn: "Durable slabs for industrial, residential and commercial use.",
      },
      {
        id: "forjados-pilares-hormigon",
        nameEs: "Forjados y pilares de hormigón armado",
        nameCa: "Forjats i pilars de formigó armat",
        nameEn: "Reinforced concrete floors and columns",
        descEs: "Estructuras de hormigón armado con cálculo y ejecución de máxima seguridad.",
        descCa: "Estructures de formigó armat amb càlcul i execució de màxima seguretat.",
        descEn: "Reinforced concrete structures designed and built to the highest safety standards.",
      },
      {
        id: "hormigonado-muros-cimientos",
        nameEs: "Hormigonado de muros y cimientos",
        nameCa: "Formigonat de murs i fonaments",
        nameEn: "Concrete walls and foundations",
        descEs: "Muros de carga y cimentaciones de hormigón con alta resistencia.",
        descCa: "Murs de càrrega i fonamentacions de formigó d'alta resistència.",
        descEn: "High-strength concrete load-bearing walls and foundations.",
      },
      {
        id: "hormigon-pulido-decorativo",
        nameEs: "Hormigón pulido y decorativo",
        nameCa: "Formigó polit i decoratiu",
        nameEn: "Polished and decorative concrete",
        descEs: "Acabados de hormigón pulido para suelos y paredes de diseño.",
        descCa: "Acabats de formigó polit per a terres i parets de disseny.",
        descEn: "Polished concrete finishes for designer floors and walls.",
      },
      {
        id: "hormigon-impreso-estampado",
        nameEs: "Hormigón impreso (estampado)",
        nameCa: "Formigó imprès (estampat)",
        nameEn: "Printed (stamped) concrete",
        descEs: "Hormigón estampado con infinidad de texturas y colores para exteriores e interiores.",
        descCa: "Formigó estampat amb infinitat de textures i colors per a exteriors i interiors.",
        descEn: "Stamped concrete in countless textures and colours for indoor and outdoor use.",
      },
      {
        id: "reparacion-estructuras-hormigon",
        nameEs: "Reparación de estructuras de hormigón",
        nameCa: "Reparació d'estructures de formigó",
        nameEn: "Concrete structure repair",
        descEs: "Diagnóstico y reparación de fisuras, carbonatación y daños en estructuras de hormigón.",
        descCa: "Diagnòstic i reparació de fissures, carbonatació i danys en estructures de formigó.",
        descEn: "Diagnosis and repair of cracks, carbonation and damage in concrete structures.",
      },
    ],
  },
  {
    id: "construccion-piscinas",
    nameEs: "Construcción de Piscinas",
    nameCa: "Construcció de Piscines",
    nameEn: "Swimming Pool Construction",
    icon: "🏊",
    services: [
      {
        id: "piscinas-hormigon-armado",
        nameEs: "Construcción de piscinas de hormigón armado",
        nameCa: "Construcció de piscines de formigó armat",
        nameEn: "Reinforced concrete swimming pool construction",
        descEs: "Piscinas de hormigón armado a medida, resistentes y durables para cualquier terreno.",
        descCa: "Piscines de formigó armat a mida, resistents i durables per a qualsevol terreny.",
        descEn: "Custom reinforced concrete pools, resistant and durable for any terrain.",
      },
      {
        id: "impermeabilizacion-vaso-piscina",
        nameEs: "Impermeabilización de vasos de piscina",
        nameCa: "Impermeabilització de vasos de piscina",
        nameEn: "Pool basin waterproofing",
        descEs: "Tratamientos impermeabilizantes de alta calidad para garantizar la estanqueidad.",
        descCa: "Tractaments impermeabilitzants d'alta qualitat per garantir l'estanqueïtat.",
        descEn: "High-quality waterproofing treatments to guarantee complete watertightness.",
      },
      {
        id: "alicatado-gresite-piscinas",
        nameEs: "Alicatado y gresite de piscinas",
        nameCa: "Enrajolat i gresite de piscines",
        nameEn: "Pool tiling and mosaic",
        descEs: "Colocación de azulejos y gresite con acabados perfectos de alta durabilidad.",
        descCa: "Col·locació de rajoles i gresite amb acabats perfectes d'alta durabilitat.",
        descEn: "Tile and mosaic installation with perfect, long-lasting finishes.",
      },
      {
        id: "sistemas-filtracion-piscina",
        nameEs: "Instalación de sistemas de filtración",
        nameCa: "Instal·lació de sistemes de filtració",
        nameEn: "Filtration system installation",
        descEs: "Instalación de bombas, filtros y sistemas de depuración para mantener el agua cristalina.",
        descCa: "Instal·lació de bombes, filtres i sistemes de depuració per mantenir l'aigua cristal·lina.",
        descEn: "Installation of pumps, filters and purification systems to keep the water crystal clear.",
      },
      {
        id: "escaleras-bordes-piscina",
        nameEs: "Escaleras y bordes de piscina",
        nameCa: "Escales i vores de piscina",
        nameEn: "Pool steps and coping",
        descEs: "Escaleras de acceso y bordes de piscina en hormigón, gresite o piedra natural.",
        descCa: "Escales d'accés i vores de piscina en formigó, gresite o pedra natural.",
        descEn: "Pool access steps and coping in concrete, mosaic or natural stone.",
      },
      {
        id: "piscinas-desbordantes-infinity",
        nameEs: "Piscinas desbordantes (infinity)",
        nameCa: "Piscines desbordants (infinity)",
        nameEn: "Infinity (overflow) pools",
        descEs: "Diseño y construcción de piscinas infinity con efecto de horizonte infinito.",
        descCa: "Disseny i construcció de piscines infinity amb efecte d'horitzó infinit.",
        descEn: "Design and construction of infinity pools with a seamless horizon effect.",
      },
      {
        id: "reforma-rehabilitacion-piscinas",
        nameEs: "Reforma y rehabilitación de piscinas existentes",
        nameCa: "Reforma i rehabilitació de piscines existents",
        nameEn: "Renovation and rehabilitation of existing pools",
        descEs: "Renovación completa de piscinas antiguas: estructura, impermeabilización y acabados.",
        descCa: "Renovació completa de piscines antigues: estructura, impermeabilització i acabats.",
        descEn: "Full renovation of existing pools: structure, waterproofing and finishes.",
      },
      {
        id: "solarium-ducha-exterior",
        nameEs: "Solarium y zona de ducha exterior",
        nameCa: "Solarium i zona de dutxa exterior",
        nameEn: "Solarium and outdoor shower area",
        descEs: "Construcción de solarium, terrazas y zonas de ducha exterior junto a la piscina.",
        descCa: "Construcció de solarium, terrasses i zones de dutxa exterior al costat de la piscina.",
        descEn: "Construction of solarium, terraces and outdoor shower areas around the pool.",
      },
      {
        id: "iluminacion-subacuatica",
        nameEs: "Iluminación subacuática",
        nameCa: "Il·luminació subaquàtica",
        nameEn: "Underwater lighting",
        descEs: "Instalación de iluminación LED subacuática para ambientar y embellecer tu piscina.",
        descCa: "Instal·lació d'il·luminació LED subaquàtica per ambientar i embellir la teva piscina.",
        descEn: "Installation of underwater LED lighting to enhance the ambience and beauty of your pool.",
      },
    ],
  },
  {
    id: "demolicion-derribo",
    nameEs: "Demolición y Derribo",
    nameCa: "Demolició i Enderroc",
    nameEn: "Demolition & Structural Removal",
    icon: "⚒️",
    services: [
      {
        id: "demolicion-total",
        nameEs: "Demolición total de edificios",
        nameCa: "Demolició total d'edificis",
        nameEn: "Total building demolition",
        descEs: "Demolición completa de edificios con gestión integral de residuos.",
        descCa: "Demolició completa d'edificis amb gestió integral de residus.",
        descEn: "Full building demolition with comprehensive waste management.",
      },
      {
        id: "demolicion-parcial",
        nameEs: "Demolición parcial y selectiva",
        nameCa: "Demolició parcial i selectiva",
        nameEn: "Partial and selective demolition",
        descEs: "Derribo controlado de partes específicas sin afectar la estructura.",
        descCa: "Enderroc controlat de parts específiques sense afectar l'estructura.",
        descEn: "Controlled demolition of specific parts without affecting the structure.",
      },
      {
        id: "derribo-tabiques",
        nameEs: "Derribo de tabiques y muros interiores",
        nameCa: "Enderroc de envans i murs interiors",
        nameEn: "Partition and interior wall removal",
        descEs: "Eliminación de tabiques para reformas de espacios interiores.",
        descCa: "Eliminació d'envans per a reformes d'espais interiors.",
        descEn: "Partition removal for interior space renovations.",
      },
      {
        id: "demolicion-forjados",
        nameEs: "Demolición de forjados y estructuras",
        nameCa: "Demolició de forjats i estructures",
        nameEn: "Slab and structural demolition",
        descEs: "Derribo técnico de forjados con total seguridad.",
        descCa: "Enderroc tècnic de forjats amb total seguretat.",
        descEn: "Technical slab demolition with complete safety.",
      },
      {
        id: "retirada-escombros",
        nameEs: "Retirada y gestión de escombros",
        nameCa: "Retirada i gestió de runes",
        nameEn: "Debris removal and management",
        descEs: "Retirada y tratamiento de escombros conforme a la normativa ambiental.",
        descCa: "Retirada i tractament de runes d'acord amb la normativa ambiental.",
        descEn: "Debris removal and treatment in accordance with environmental regulations.",
      },
      {
        id: "maquinaria-pesada",
        nameEs: "Demolición con maquinaria pesada",
        nameCa: "Demolició amb maquinària pesada",
        nameEn: "Heavy machinery demolition",
        descEs: "Equipos de demolición pesada para proyectos de gran envergadura.",
        descCa: "Equips de demolició pesada per a projectes de gran envergadura.",
        descEn: "Heavy demolition equipment for large-scale projects.",
      },
      {
        id: "demolicion-manual",
        nameEs: "Demolición manual de precisión",
        nameCa: "Demolició manual de precisió",
        nameEn: "Manual precision demolition",
        descEs: "Demolición cuidadosa en espacios reducidos o con riesgo estructural.",
        descCa: "Demolició acurada en espais reduïts o amb risc estructural.",
        descEn: "Careful demolition in confined spaces or with structural risk.",
      },
      {
        id: "vaciado-locales",
        nameEs: "Vaciado de locales y pisos",
        nameCa: "Buidatge de locals i pisos",
        nameEn: "Premises and flat clearance",
        descEs: "Vaciado completo de locales y viviendas antes de la reforma.",
        descCa: "Buidatge complet de locals i habitatges abans de la reforma.",
        descEn: "Complete clearance of premises and flats before renovation.",
      },
      {
        id: "desescombro",
        nameEs: "Desescombro y limpieza de obra",
        nameCa: "Desruna i neteja d'obra",
        nameEn: "Site clearing and cleaning",
        descEs: "Limpieza y desescombro profesional tras trabajos de construcción.",
        descCa: "Neteja i desruna professional després de treballs de construcció.",
        descEn: "Professional site clearing and cleaning after construction works.",
      },
      {
        id: "gestion-residuos-rcd",
        nameEs: "Gestión y transporte de residuos de construcción (RCD)",
        nameCa: "Gestió i transport de residus de construcció (RCD)",
        nameEn: "Construction waste management and transport (CWM)",
        descEs: "Gestión integral y transporte de residuos de construcción cumpliendo toda la normativa.",
        descCa: "Gestió integral i transport de residus de construcció complint tota la normativa.",
        descEn: "Comprehensive construction waste management and transport in full compliance.",
      },
    ],
  },
];

export function getAllServices() {
  return SERVICE_CATEGORIES.flatMap((cat) =>
    cat.services.map((s) => ({ ...s, categoryId: cat.id, categoryNameEs: cat.nameEs }))
  );
}

export function getServiceName(service: ServiceItem, locale: string): string {
  if (locale === "ca") return service.nameCa;
  if (locale === "en") return service.nameEn;
  return service.nameEs;
}

export function getCategoryName(category: ServiceCategory, locale: string): string {
  if (locale === "ca") return category.nameCa;
  if (locale === "en") return category.nameEn;
  return category.nameEs;
}
